### ISSUE TITLE
WebViewer keep showing loading in IOS Device 

### ISSUE THREAD

**Issue by jsBiztech** [PDFTron/webviewer-offline-sample#1]
I have downloaded sample webViewer and followed steps on below link : 
[https://pspdfkit.com/guides/web/current/standalone/integration/#prerequisites](https://pspdfkit.com/guides/web/current/standalone/integration/#prerequisites)

I have setup sample webViewer on server i am trying to access through URL.

eg : [https://web-examples.pspdfkit.com/hello](https://web-examples.pspdfkit.com/hello)

and in my **ionic3 app** i am trying to load that URL using **InAppBrowser plugin**, although Its working perfect in Browser and android application but in IOS application its keep showing loading.

**NOTE:** Its working in Iphone Browser the issue is in the application.

Can you please guide!

**Comment by mparizeau-pdftron** [comment]
It looks like you're using the PSPDFKit SDK and not PDFTron's WebViewer. This repo is for the PDFTron WebViewer which you can download from here https://www.pdftron.com/documentation/web/guides/download-and-run-samples

If you have any particular questions about using WebViewer then we'll be happy to help!

**Comment by jsBiztech** [comment]
Hello @mparizeau-pdftron I think I have mistakenly added pspdfkit Link in my query.
The link is same as the one shared by you and the issue is as described above.
Please look into it.

**Comment by mparizeau-pdftron** [comment]
Since this repo is about the WebViewer offline sample I'd recommend you submit your question here https://www.pdftron.com/support and if you could provide an example application with your submission that isn't able to load that would be very helpful for us to help debug. Thanks!
